[phases.setup]
nixPkgs = ["nodejs_22", "npm-10_x"]

[phases.build]
cmds = [
  "npm ci --omit=dev", # install dependencies production + dev kalau dibutuhkan
  "npx vite build"
]

[start]
cmd = "npx vite preview --port $PORT --host"

[variables]
NIXPACKS_SPA = "1"
NIXPACKS_SPA_OUTPUT_DIR = "dist"