[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.build]
cmds = [
  "npm ci",
  "npm run build"
]

[start]
cmd = "npm run start"

[variables]
NIXPACKS_SPA = "1"
NIXPACKS_SPA_OUTPUT_DIR = "dist"
